customSelectors:
  enabled: false
  selectors: ""

envs:
  - name: CLI_CRON
    value: '5,35 * * * *'
  - name: SERVICE_CRON
    value: '0 */4 * * *'
  - name: LABELER_CRON
    value: '0 0 * * *'
  - name: ENABLE_SERVICE_IDLER
    value: true
  - name: ENABLE_CLI_IDLER
    value: true
  - name: POD_CHECK_INTERVAL
    value: 4
  - name: ELASTIC_CHECK_INTERVAL
    value: 4h
  - name: LAGOON_API_URL
    value: ''
  - name: LAGOON_API_TOKEN
    value: ''
  - name: ELASTICSEARCH_USER
    value: ''
  - name: ELASTICSEARCH_PASS
    value: ''
  - name: ELASTICSEARCH_HOST
    value: ''

# the following values are defaults which may be overridden
args:
- "--metrics-addr=127.0.0.1:8080"
- "--enable-leader-election=true"

# any extra args can be defined
extraArgs:

# override .Chart.Name
nameOverride: ""

image:
  repository: amazeeio/lagoon-idler
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

serviceAccount:
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# this is a sidecar in the same pod as the dioscuri container
kubeRBACProxy:
  image:
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    pullPolicy: IfNotPresent
    tag: v0.4.1

  securityContext: {}

  resources: {}
