apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ses-relay.fullname" . }}
  labels:
    {{- include "ses-relay.labels" . | nindent 4 }}
spec:
  {{- if .Values.replicaCount }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ses-relay.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ses-relay.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
              - aws-smtp-relay
              - '-e'
              - {{ .Values.ses.awsConfigSet }}
              {{- if .Values.ses.deniedSenderExpression }}
              - '-d'
              - {{ .Values.ses.deniedSenderExpression }}
              {{- end }}
              {{- if .Values.ses.allowedSenderExpression }}
              - '-l'
              - {{ .Values.ses.allowedSenderExpression }}
              {{- end }}
              {{- if .Values.ses.allowedClientIPs }}
              - '-i'
              - '{{ join ',' .Values.ses.allowedClientIPs }}'
              {{- end }}
          env:
            {{- if .Values.aws }}
            - name: AWS_REGION
              value: {{ .Values.aws.region }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ required "AWS Access key must be provided" .Values.aws.accessKey }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ required "AWS Secret key must be provided" .Values.aws.accessSecretKey }}
            {{- end }}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.ses.port }}
            timeoutSeconds: 1
          ports:
            - containerPort: {{ .Values.ses.port }}
              name: smtp-port
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.ses.port }}
            timeoutSeconds: 1
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
