{{- if .Values.sshkey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lagoon-idler.fullname" . }}-sshkey
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: {{ .Values.sshkey | b64enc }}
{{- end }}
