apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lagoon-idler.serviceAccountName" . }}
  labels:
    {{- include "lagoon-idler.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}