apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aergia.fullname" . }}-manager
  labels:
    {{- include "aergia.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "aergia.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ include "aergia.fullname" . }}-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aergia.fullname" . }}-proxy
  labels:
    {{- include "aergia.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "aergia.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ include "aergia.fullname" . }}-proxy
  apiGroup: rbac.authorization.k8s.io