{{- if .Values.templates.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aergia.fullname" . }}-templates
data:
  error.html: |
{{ .Values.templates.error | indent 4 }}
  unidle.html: |
{{ .Values.templates.unidle | indent 4 }}
{{- end}}