apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aergia.fullname" . }}
  labels:
    {{- include "aergia.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aergia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aergia.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aergia.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - "--metrics-bind-address=:8443"
            - "--leader-elect=true"
            {{- if .Values.idling.enabled }}
            - "--prometheus-endpoint={{ .Values.idling.prometheusEndpoint }}"
            - "--prometheus-interval={{ .Values.idling.prometheusCheckInterval }}"
            - "--pod-check-interval={{ .Values.idling.podCheckInterval }}"
            - "--cli-idler-cron={{ .Values.idling.cliCron }}"
            - "--service-idler-cron={{ .Values.idling.serviceCron }}"
            - "--refresh-interval={{ .Values.idling.refreshInterval }}"
            {{- end }}
            {{- with .Values.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
          {{- if .Values.idling.enabled }}
          {{- with .Values.idling.enableServiceIdler }}
            - name: ENABLE_SERVICE_IDLER
              value: {{ . | quote }}
          {{- end }}
          {{- with .Values.idling.enableCLIIdler }}
            - name: ENABLE_CLI_IDLER
              value: {{ . | quote }}
          {{- end }}
          {{- with .Values.idling.dryRun }}
            - name: DRY_RUN
              value: {{ . | quote }}
          {{- end }}
          {{- else }}
            - name: ENABLE_SERVICE_IDLER
              value: "false"
            - name: ENABLE_CLI_IDLER
              value: "false"
          {{- end }}
          {{- if .Values.templates.enabled}}
            - name: ERROR_FILES_PATH
              value: "/templates"
          {{- end}}
          {{- if .Values.customSelectors.enabled }}
            - name: SELECTORS_YAML_FILE
              value: "/custom/selectors.yaml"
          {{- end }}
          {{- range $name, $value := .Values.extraEnvs }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- if .Values.unidling.verifyRequests.enabled }}
          envFrom:
            - secretRef:
                name: {{ include "aergia.fullname" . }}
          {{- end }}
          ports:
            - containerPort: 5000
              name: backend
            - containerPort: 8443
              name: https
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.unidling.ipAllowList}}
            - name: {{ include "aergia.fullname" . }}-allowedips
              mountPath: "/lists/allowedips"
              subPath: "allowedips"
              readOnly: true
          {{- end}}
          {{- if .Values.unidling.ipBlockList}}
            - name: {{ include "aergia.fullname" . }}-blockedips
              mountPath: "/lists/blockedips"
              subPath: "blockedips"
              readOnly: true
          {{- end}}
          {{- if .Values.unidling.agentAllowList}}
            - name: {{ include "aergia.fullname" . }}-allowedagents
              mountPath: "/lists/allowedagents"
              subPath: "allowedagents"
              readOnly: true
          {{- end}}
          {{- if .Values.unidling.agentBlockList}}
            - name: {{ include "aergia.fullname" . }}-blockedagents
              mountPath: "/lists/blockedagents"
              subPath: "blockedagents"
              readOnly: true
          {{- end}}
          {{- if .Values.templates.enabled}}
          {{- if .Values.templates.error}}
            - name: {{ include "aergia.fullname" . }}-error
              mountPath: "/templates/error.html"
              subPath: "error.html"
              readOnly: true
          {{- end}}
          {{- if .Values.templates.forced}}
            - name: {{ include "aergia.fullname" . }}-forced
              mountPath: "/templates/forced.html"
              subPath: "forced.html"
              readOnly: true
          {{- end}}
          {{- if .Values.templates.unidle}}
            - name: {{ include "aergia.fullname" . }}-unidle
              mountPath: "/templates/unidle.html"
              subPath: "unidle.html"
              readOnly: true
          {{- end}}
          {{- end}}
          {{- if .Values.customSelectors.enabled }}
            - name: {{ include "aergia.fullname" . }}-selectors
              mountPath: "/custom"
              readOnly: true
          {{- end }}
      volumes:
      {{- if .Values.unidling.ipAllowList}}
        - name: {{ include "aergia.fullname" . }}-allowedips
          configMap:
            name: {{ include "aergia.fullname" . }}-lists
            items:
              - key: "allowedips"
                path: "allowedips"
      {{- end }}
      {{- if .Values.unidling.ipBlockList}}
        - name: {{ include "aergia.fullname" . }}-blockedips
          configMap:
            name: {{ include "aergia.fullname" . }}-lists
            items:
              - key: "blockedips"
                path: "blockedips"
      {{- end }}
      {{- if .Values.unidling.agentAllowList}}
        - name: {{ include "aergia.fullname" . }}-allowedagents
          configMap:
            name: {{ include "aergia.fullname" . }}-lists
            items:
              - key: "allowedagents"
                path: "allowedagents"
      {{- end }}
      {{- if .Values.unidling.agentBlockList}}
        - name: {{ include "aergia.fullname" . }}-blockedagents
          configMap:
            name: {{ include "aergia.fullname" . }}-lists
            items:
              - key: "blockedagents"
                path: "blockedagents"
      {{- end }}
      {{- if .Values.templates.enabled}}
      {{- if .Values.templates.error}}
        - name: {{ include "aergia.fullname" . }}-error
          configMap:
            name: {{ include "aergia.fullname" . }}-templates
            items:
              - key: "error.html"
                path: "error.html"
      {{- end }}
      {{- if .Values.templates.forced}}
        - name: {{ include "aergia.fullname" . }}-forced
          configMap:
            name: {{ include "aergia.fullname" . }}-templates
            items:
              - key: "forced.html"
                path: "forced.html"
      {{- end }}
      {{- if .Values.templates.unidle}}
        - name: {{ include "aergia.fullname" . }}-unidle
          configMap:
            name: {{ include "aergia.fullname" . }}-templates
            items:
              - key: "unidle.html"
                path: "unidle.html"
      {{- end }}
      {{- end}}
      {{- if .Values.customSelectors.enabled }}
        - name: {{ include "aergia.fullname" . }}-selectors
          configMap:
            name: {{ include "aergia.fullname" . }}-selectors
            items:
              - key: "selectors.yaml"
                path: "selectors.yaml"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
