apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aergia.fullname" . }}
  labels:
    {{- include "aergia.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "aergia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aergia.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aergia.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: kube-rbac-proxy
          securityContext:
            {{- toYaml .Values.kubeRBACProxy.securityContext | nindent 12 }}
          image: "{{ .Values.kubeRBACProxy.image.repository }}:{{ .Values.kubeRBACProxy.image.tag }}"
          imagePullPolicy: {{ .Values.kubeRBACProxy.image.pullPolicy }}
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8080/"
            - "--logtostderr=true"
            - "--v=10"
          ports:
            - containerPort: 8443
              name: https
          resources:
            {{- toYaml .Values.kubeRBACProxy.resources | nindent 12 }}
        - name: manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          {{- if .Values.extraArgs }}
          args:
          {{- with .Values.extraArgs }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: 5000
              name: backend
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.templates.enabled}}
          env:
            - name: ERROR_FILES_PATH
              value: "/templates"
          volumeMounts:
            - name: {{ include "aergia.fullname" . }}-templates
              mountPath: "/templates"
              readOnly: true
          {{- end}}
      {{- if .Values.templates.enabled}}
      volumes:
        - name: {{ include "aergia.fullname" . }}-templates
          configMap:
            name: {{ include "aergia.fullname" . }}-templates
            items:
            - key: "error.html"
              path: "error.html"
            - key: "unidle.html"
              path: "unidle.html"
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
