apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aergia.fullname" . }}-leader-election
  labels:
    {{- include "aergia.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - ingress/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - '*'
  resources:
  - ingresses
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch