{{- if .Values.unidling.verifyRequests.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "aergia.fullname" . }}
  labels:
    {{- include "aergia.labels" . | nindent 4 }}
stringData:
  VERIFIED_UNIDLING: {{ .Values.unidling.verifyRequests.enabled | quote }}
  VERIFY_SECRET: {{ .Values.unidling.verifyRequests.secret | quote }}
{{- end}}
