---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aergia.fullname" . }}
  labels:
    {{- include "aergia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "aergia.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aergia.fullname" . }}-backend
  labels:
    {{- include "aergia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: backend
      protocol: TCP
      name: backend
  selector:
    {{- include "aergia.selectorLabels" . | nindent 4 }}
{{- if .Values.metrics.enabled }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "aergia.fullname" . }}-metrics
  labels:
    {{- include "aergia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: metrics
      protocol: TCP
      port: 9912
      targetPort: metrics
  selector:
    {{- include "aergia.selectorLabels" . | nindent 4 }}
{{- end }}