apiVersion: v2
name: monitoring
description: >
  A Helm chart for Kubernetes which installs a Prometheus/Grafana monitoring
  stack.
home: https://github.com/amazeeio/charts
icon: https://raw.githubusercontent.com/amazeeio/charts/main/icon.png
maintainers:
- name: smlx
  email: scott.leggett@amazee.io
  url: https://amazee.io

type: application

version: 0.1.0

appVersion: "0.1.0"  # this value currently not used

dependencies:
- name: kube-prometheus-stack
  version: ~17.2.1
  repository: https://prometheus-community.github.io/helm-charts
  condition: kube-prometheus-stack.enabled
