apiVersion: v1
kind: Service
metadata:
  name: {{ include "principio.fullname" . }}
  labels:
    {{- include "principio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: https
    protocol: TCP
    name: https
  selector:
    {{- include "principio.selectorLabels" . | nindent 4 }}
