apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dbaas-operator.fullname" . }}
  labels:
    {{- include "dbaas-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dbaas-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dbaas-operator.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "dbaas-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: manager
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
          name: backend
        - containerPort: 8443
          name: https
        command:
        - /manager
        args:
        - --metrics-bind-address=:8443
        - --leader-elect=true
        {{- with .Values.extraArgs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.enableMariaDBProviders }}
        - --enable-mariadb-providers
        {{- end }}
        {{- if .Values.enableMongoDBProviders }}
        - --enable-mongodb-providers
        {{- end }}
        {{- if .Values.enablePostreSQLProviders }}
        - --enable-postgresql-providers
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
