apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fastly-controller.fullname" . }}-manager
  labels:
    {{- include "fastly-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - ingress
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - ingress/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - '*'
  resources:
  - ingresses
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fastly-controller.fullname" . }}-proxy
  labels:
    {{- include "fastly-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create