apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fastly-controller.fullname" . }}-manager
  labels:
    {{- include "fastly-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fastly-controller.fullname" . }}-manager
subjects:
- kind: ServiceAccount
  name: {{ include "fastly-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fastly-controller.fullname" . }}-proxy
  labels:
    {{- include "fastly-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fastly-controller.fullname" . }}-proxy
subjects:
- kind: ServiceAccount
  name: {{ include "fastly-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
