apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastly-controller.fullname" . }}
  labels:
    {{- include "fastly-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
    port: {{ .Values.service.port }}
    targetPort: https
    protocol: TCP
  selector:
    {{- include "fastly-controller.selectorLabels" . | nindent 4 }}
